name: codacy-coverage-reporter

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Run codacy-coverage-reporter
        uses: ./
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
